language: php

php:
  - 7.3

matrix:
  fast_finish: true

install:
  - composer install --no-interaction -o

script:
  - composer build-all

sudo: false

cache:
  directories:
    - $HOME/.composer/cache